// ./sidebarsPapers.js

// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//     // ID của sidebar này có thể được đặt tùy ý, ví dụ 'paperSidebar'
//     // ID này sẽ được sử dụng nếu bạn muốn liên kết đến sidebar này từ navbar
//     // bằng type: 'docSidebar' và chỉ định docsPluginId: 'papers'
//     paperSidebar: [
//       {
//         type: 'category',
//         label: 'Giới thiệu chung',
//         link: {
//           type: 'generated-index', // Tự động tạo trang index cho category
//           title: 'Tổng quan về các Paper',
//           description: 'Đây là danh sách các bài paper quan trọng.',
//           slug: '/category/overview', // Đường dẫn URL cho trang index này
//         },
//         items: [
//           'intro', // ID của paper (tên file không có .md hoặc front matter id)
//           'linear-algebra/abc',
//         ],
//       },
//       {
//         type: 'category',
//         label: 'Chủ đề A',
//         items: ['linear-algebra/abc'],
//       },
//       // Thêm các category hoặc paper khác
//     ],
//   };
  
//   module.exports = sidebars;


  // ./sidebarsPapers.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    statisticsSidebar: [ // ID của sidebar này (ví dụ: paperSidebar)
      {type: 'autogenerated', dirName: '.'}
    ],
  };
  
  module.exports = sidebars;





//   @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
//   */
//  const sidebars = {
//    // By default, Docusaurus generates a sidebar from the docs folder structure
//    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
 
//    // But you can create a sidebar manually
//    /*
//    tutorialSidebar: [
//      'intro',
//      'hello',
//      {
//        type: 'category',
//        label: 'Tutorial',
//        items: ['tutorial-basics/create-a-document'],
//      },
//    ],
//     */
//  };
 
//  export default sidebars;
 