# ...
steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Set up Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '18' # Hoặc phiên bản Node.js bạn đang dùng
      cache: 'npm' # THAY ĐỔI Ở ĐÂY
  - name: Install dependencies
    run: npm ci # THAY ĐỔI Ở ĐÂY
  - name: Build
    run: npm run build # THAY ĐỔI Ở ĐÂY